[project]
name = "warehouse-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.10"
dependencies = [
    "boto3>=1.43.36",
    "dbt-duckdb>=1.10.1",
    "faker>=38.2.0",
    "fastapi>=0.123.10",
    "pandas>=2.3.3",
    "pyarrow>=24.0.0",
    "pyodbc>=5.3.0",
    "python-dotenv>=1.2.2",
    "requests>=2.34.2",
    "schedule>=1.2.2",
    "sqlalchemy>=2.0.51",
    "uvicorn[standard]>=0.38.0",
]
