warehouse_dbt:
  target: dev
  outputs:
    dev:
      type: duckdb
      path: ':memory:' # Usa a memória RAM para processar tudo super rápido
      threads: 6
      extensions:
        - httpfs # Necessário para ler/escrever no S3
      settings:
        s3_region: "{{ env_var('AWS_REGION') }}"
        s3_access_key_id: "{{ env_var('AWS_ACCESS_KEY_ID') }}"
        s3_secret_access_key: "{{ env_var('AWS_SECRET_ACCESS_KEY') }}"
