{{ config(
    location="s3://" ~ env_var('S3_BUCKET_NAME') ~ "/04_gold/sqlserver/Tecpel/gld_fct_estoque.parquet"
) }}

WITH CTE_LocalEstoqueAtivo AS (
    SELECT * 
    FROM {{ ref('gld_dim_local_estoque') }}
    WHERE STATUS = 'A' AND COD_GESTOR IS NOT NULL
),

CTE_ULT_SAIDA AS (
    SELECT E.IDPRD
         , E.IDMOV
         , M.CODTMV
         , E.CODFILIAL
         , E.CODLOC
         , E.CODCOLIGADA
         , E.DATAMOVIMENTO AS DATA_ULT_VENDA
         , ROW_NUMBER() OVER(PARTITION BY E.CODLOC, E.IDPRD ORDER BY E.SEQUENCIAL DESC) AS NL
      FROM {{ ref('slv_tecpel_trelsld') }} E
      LEFT JOIN {{ ref('slv_tecpel_tmov') }} M
         ON E.CODCOLIGADA = M.CODCOLIGADA
        AND E.IDMOV = M.IDMOV
      INNER JOIN {{ ref('gld_dim_tipo_movimento') }} TM
         ON M.CODTMV = TM.CODTMV
        AND TM.CATEGORIA = 'Faturamento'
     WHERE E.CODCOLIGADA = 2
       AND E.TOTALMOV IS NOT NULL
       AND E.DATAMOVIMENTO BETWEEN '2005-01-01' AND CURRENT_DATE
       AND E.QTDESAIDA IS NOT NULL
),

CTE_ULT_ENTRADA AS (
    SELECT IDPRD
         , CODFILIAL
         , CODLOC
         , CODCOLIGADA
         , DATAMOVIMENTO AS DATA_ULT_ENTRADA
         , ROW_NUMBER() OVER(PARTITION BY CODLOC, IDPRD ORDER BY SEQUENCIAL DESC) AS NL
      FROM {{ ref('slv_tecpel_trelsld') }}
     WHERE CODCOLIGADA = 2
       AND TOTALMOV IS NOT NULL
       AND DATAMOVIMENTO BETWEEN '2005-01-01' AND CURRENT_DATE
       AND QTDEENTRADA IS NOT NULL
)

SELECT A.CODFILIAL || '.' || A.CODLOC AS IDLOC
     , A.CODFILIAL
     , A.CODLOC
     , A.IDPRD
     , D.NOME AS LOCAL_ESTOQUE
     , CAST(ROUND((A.QTD_SALDO * E.ESPESSURA), 2) AS NUMERIC(18,2)) AS PESO_SALDO
     , E.ESPESSURA AS PESOLIQUIDO
     , A.QTD_SALDO
     , A.FIN_SALDO 
     , A.DATA_SALDO
     , MONTH(A.DATA_SALDO + INTERVAL 1 MONTH) AS MES_DESLOC
     , YEAR(A.DATA_SALDO + INTERVAL 1 MONTH) AS ANO_DESLOC
     , MAKE_DATE(YEAR(A.DATA_SALDO + INTERVAL 1 MONTH), MONTH(A.DATA_SALDO + INTERVAL 1 MONTH), 1) AS DATA_DESLOC
     , CAST(ROUND(A.FIN_SALDO / NULLIF(A.QTD_SALDO, 0), 4) AS NUMERIC(16,4)) AS CUSTO_MEDIO
     , CAST(ROUND(A.FIN_SALDO / NULLIF(A.QTD_SALDO, 0) / NULLIF(E.ESPESSURA, 0), 4) AS NUMERIC(10,4)) AS CUSTO_UNIT_MEDIO
     , SUM(A.FIN_SALDO) OVER(PARTITION BY A.CODFILIAL, A.CODLOC, C.CODSUBGRUPO, C.PROCEDENCIA, A.DATA_SALDO) / NULLIF(SUM(A.QTD_SALDO * E.ESPESSURA) OVER(PARTITION BY A.CODFILIAL, A.CODLOC, C.CODSUBGRUPO, C.PROCEDENCIA, A.DATA_SALDO), 0) AS CUSTO_POND_SUBGRUPO
     , F.COD_GESTOR
     , C.TIPOFAM
     , C.CODFAM
     , C.CODGRUPO
     , C.CODSUBGRUPO
     , E.CODIGOREDUZIDO
     , C.PROCEDENCIA AS PROCEDENCIA_PRD
     , EN.DATA_ULT_ENTRADA
     , SA.DATA_ULT_VENDA
     , DATE_DIFF('day', COALESCE(SA.DATA_ULT_VENDA, EN.DATA_ULT_ENTRADA), CURRENT_DATE) AS DIAS_SEM_VENDA
     , A.dt_extracao
     , A.datasource
FROM {{ ref('slv_tecpel_estoque_saldo_produto_mes') }} A
LEFT JOIN {{ ref('gld_dim_produto') }} C
    ON A.IDPRD = C.IDPRD
LEFT JOIN {{ ref('gld_dim_local_estoque') }} D
    ON A.CODFILIAL = D.CODFILIAL
   AND A.CODLOC = D.CODLOC
LEFT JOIN {{ ref('slv_tecpel_tprd') }} E
    ON A.IDPRD = E.IDPRD
   AND E.CODCOLIGADA = 2
INNER JOIN CTE_LocalEstoqueAtivo F
    ON A.CODFILIAL = F.CODFILIAL
   AND A.CODLOC = F.CODLOC
LEFT JOIN CTE_ULT_SAIDA SA
        ON A.CODFILIAL = SA.CODFILIAL
       AND A.CODLOC = SA.CODLOC
       AND A.IDPRD = SA.IDPRD
       AND SA.NL = 1
LEFT JOIN CTE_ULT_ENTRADA EN
        ON A.CODFILIAL = EN.CODFILIAL
       AND A.CODLOC = EN.CODLOC
       AND A.IDPRD = EN.IDPRD
       AND EN.NL = 1
